project_id = "xzbacghvhlqolbamgfed"

[functions.gemini-chat]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = false

[functions.verify-email-code]
verify_jwt = false

[functions.enhance-image]
verify_jwt = false
